import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{ArrowUpRight,ExternalLink,Globe,Mail,Phone,Menu,X,MapPin,Sparkles,Code2,Database,Palette,BarChart3,GraduationCap,Award}from'lucide-react';import'./index.css';import portrait from'./assets/ishvari.jpg';
const profile={email:'borsutkarishvari@gmail.com',phone:'9271870570',linkedin:'https://www.linkedin.com/in/ishvari-borsutkar-1b80b33b8'};
const projects=[
{title:'CustomJersey',subtitle:'Personalized Sportswear Ordering Platform',desc:'A group project focused on making custom jersey selection, personalization and ordering more organized for customers and easier to manage.',tags:['HTML','Tailwind CSS','JavaScript','Python','Node.js','MongoDB']},
{title:'PostSahayak',subtitle:'Rural Government Scheme Discovery Platform',desc:'A group project designed to help rural users discover relevant government schemes through simple category-based access, including roles such as students and farmers.',tags:['React','HTML','Tailwind CSS','Python / FastAPI','MongoDB Atlas']},
{title:'Lost & Found',subtitle:'Campus Item Recovery System',desc:'A group project experience focused on helping users report and discover lost or found items in a campus environment.',tags:[]},
{title:'Library Management System',subtitle:'Basic Record Management Application',desc:'A basic academic mini project supporting essential library record operations such as insert, update, delete and data handling.',tags:['HTML','CSS','SQL']},
{title:'Personal Portfolio',subtitle:'Interactive React Portfolio',desc:'A responsive portfolio built with React to present my education, skills, projects, credentials and interests through reusable components and interactive UI.',tags:['React.js','JavaScript','HTML','CSS','Vite','Lucide React']}];
const credentials=[
{type:'Certificate',title:'Data Analytics Internship',org:'Internship Studio',date:'15 Jun 2026 – 19 Aug 2026',desc:'Successfully completed an online Data Analytics Internship with practical exposure to the analytics workflow and hands-on analytical concepts.',meta:'Data Analytics • Online Internship'},
{type:'Certificate',title:'Database Management System Course',org:'SEED Infotech Limited, Pune',date:'27 Jan 2026 – 02 Feb 2026',desc:'Completed a DBMS course covering SQL, database design, normalization and data handling concepts.',meta:'SQL • Database Design • Normalization'},
{type:'Certificate',title:'Full Stack Java Introductory Course',org:'SEED Infotech Limited, Pune',date:'26 Jul 2025 – 01 Aug 2025',desc:'Completed an introductory course covering foundational Java programming, frontend and backend development concepts, and basic database connectivity.',meta:'Java • Frontend • Backend • Database Connectivity'},
{type:'Certificate',title:'NPTEL Public Speaking',org:'NPTEL / IIT Roorkee',date:'Jul – Oct 2024 • 12-week course',desc:'Successfully completed the Public Speaking certification course, strengthening communication confidence and presentation skills.',meta:'Communication • Presentation Skills'},
{type:'Hackathons',title:'CodeBit 4.0 Hackathon',org:'Gharda Institute of Technology & Management',date:'11–12 Mar 2026',desc:'Participated in the CodeBit 4.0 Hackathon, collaborating on problem-solving activities and exploring technical solutions while developing teamwork and analytical thinking.',meta:'Participation • Problem Solving • Teamwork'},
{type:'Extracurricular',title:'Synergy 2K26 — Antakshari',org:'Gharda Institute of Technology & Management',date:'27–28 Feb 2026',desc:'Participated in the Antakshari cultural event, gaining experience in confidence, teamwork and coordination.',meta:'Cultural Participation • Teamwork • Coordination'}];
function SectionTitle({eyebrow,title,text}){return <div className="section-head"><span>{eyebrow}</span><h2>{title}</h2>{text&&<p>{text}</p>}</div>}
function Navbar({active,darkMode,onToggleTheme}){const[open,setOpen]=useState(false);const links=[['home','Home'],['about','About'],['education','Education'],['skills','Skills'],['projects','Projects'],['credentials','Credentials'],['contact','Contact']];return <nav className="nav"><div className="nav-inner"><a className="brand" href="#home"><span>IB</span><strong>Ishvari<span>.</span></strong></a><button className="menu-btn" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><div className={'nav-links '+(open?'open':'')}>{links.map(([id,label])=><a key={id} className={active===id?'active':''} href={'#'+id} onClick={()=>setOpen(false)}>{label}</a>)}</div><button type="button" className="theme-toggle" onClick={onToggleTheme} aria-label="Toggle light and dark mode">{darkMode?'☀️ Light':'🌙 Dark'}</button><a className="nav-contact" href="#contact">Let's Connect <ArrowUpRight size={16}/></a></div></nav>} 
function Hero(){return <section id="home" className="hero section"><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow-pill"><Sparkles size={15}/> Computer Science & AI/ML Undergraduate</div><h1>Building ideas into <em>digital experiences.</em></h1><p className="hero-lead">I'm <b>Ishvari Swapnil Borsutkar</b>, a third-year CSE (AI/ML) undergraduate exploring web design, data, databases and practical technology projects.</p><div className="hero-actions"><a className="btn primary" href="#projects">Explore My Work <ArrowUpRight size={18}/></a><a className="btn secondary" href="#contact">Let's Connect</a></div><div className="quick-facts"><span><MapPin size={15}/> Khed, Ratnagiri</span><span><Mail size={15}/> borsutkarishvari@gmail.com</span></div></div><div className="hero-photo-wrap"><div className="photo-orbit"></div><div className="hero-photo"><img src={portrait} alt="Ishvari Swapnil Borsutkar"/></div><div className="floating-card card-top"><span>8.89</span><small>Engineering Pointer</small></div><div className="floating-card card-bottom"><span>93.20%</span><small>SSC Score</small></div></div></div></section>}
function About(){return <section id="about" className="section"><div className="container"><SectionTitle eyebrow="ABOUT ME" title="Curious about technology. Focused on building useful things." text="A short introduction to what I enjoy learning and creating."/><div className="about-grid"><div className="about-main"><p>I'm a third-year Bachelor of Engineering student specializing in Computer Science and Engineering with Artificial Intelligence & Machine Learning. I enjoy turning ideas into simple, useful digital experiences and learning how technology can solve everyday problems.</p><p>My current interests span <strong>web design, databases, data analytics and practical software projects</strong>. I have worked with HTML, CSS, JavaScript, React, SQL/MySQL and MongoDB, while continuing to strengthen my Python and development skills.</p><p>Alongside technical learning, I value communication, presentation, visual design and teamwork. I like exploring new tools, participating in collaborative projects and steadily building a stronger foundation for my future in technology.</p></div><div className="about-highlights"><div><Code2/><span>Web & UI</span><small>HTML, CSS, JavaScript, React</small></div><div><Database/><span>Data & Databases</span><small>SQL, MySQL, MongoDB, DBMS</small></div><div><BarChart3/><span>Analytics</span><small>Excel & data-oriented learning</small></div><div><Palette/><span>Creative Skills</span><small>Presentation & poster design</small></div></div></div></div></section>}
function Education(){return <section id="education" className="section tinted"><div className="container"><SectionTitle eyebrow="EDUCATION" title="Learning with a practical mindset."/><div className="edu-card"><div className="edu-icon"><GraduationCap/></div><div><div className="edu-top"><span className="tag">2024 — Present</span><span className="tag soft">3rd Year</span></div><h3>Bachelor of Engineering — Computer Science & Engineering (AI/ML)</h3><p>Gharda Institute of Technology & Management</p><div className="edu-stats"><div><b>8.89</b><small>Engineering Pointer</small></div><div><b>Top 5</b><small>Semester 3</small></div><div><b>78%</b><small>HSC</small></div><div><b>93.20%</b><small>SSC</small></div></div></div></div></div></section>}
const skills=[['HTML','Web Structure','Comfortable with core concepts'],['CSS','Styling','Understanding of layouts & styling'],['JavaScript','Web Interactivity','Currently learning'],['React.js','UI Development','Used in projects; building foundations'],['Python','Programming','Basic / learning'],['Java','OOP Concepts','Basic concepts'],['SQL / MySQL','Databases','Working knowledge'],['MongoDB','NoSQL','Familiar with basics'],['Excel','Data & Analysis','Practical learning'],['DBMS','Database Concepts','SQL, design & normalization'],['PowerPoint','Presentation','Strong presentation tool usage'],['Web & Poster Design','Creative','Visual communication & design']];
function Skills(){return <section id="skills" className="section"><div className="container"><SectionTitle eyebrow="SKILLS" title="A growing toolkit, one project at a time." text="Technologies and capabilities I am learning and applying through academics and projects."/><div className="skills-grid">{skills.map(([a,b,c])=><div className="skill-card" key={a}><div className="skill-mark">{a.slice(0,2)}</div><div><h3>{a}</h3><b>{b}</b><p>{c}</p></div></div>)}</div></div></section>}
function Projects(){return <section id="projects" className="section tinted"><div className="container"><SectionTitle eyebrow="PROJECTS" title="Projects that turn classroom learning into practice."/><div className="project-grid">{projects.map((p,i)=><article className="project-card" key={p.title}><div className="project-number">0{i+1}</div><div className="project-body"><span className="project-type">{i<2?'GROUP PROJECT':'ACADEMIC PROJECT'}</span><h3>{p.title}</h3><h4>{p.subtitle}</h4><p>{p.desc}</p>{p.tags.length>0&&<div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div>}</div><div className="project-arrow"><ArrowUpRight/></div></article>)}</div></div></section>}
function Credentials(){const[filter,setFilter]=useState('All');const types=['All','Certificate','Hackathons','Extracurricular'];const list=filter==='All'?credentials:credentials.filter(c=>c.type===filter);return <section id="credentials" className="section"><div className="container"><SectionTitle eyebrow="CREDENTIALS" title="Certificates, participation & milestones." text="A collection of certifications, internships and activities that have shaped my learning journey so far."/><div className="filters">{types.map(t=><button className={filter===t?'selected':''} onClick={()=>setFilter(t)} key={t}>{t}</button>)}</div><div className="credential-grid">{list.map(c=><article className="credential-card" key={c.title}><div className="cred-icon"><Award size={21}/></div><div className="cred-content"><span className="cred-type">{c.type}</span><h3>{c.title}</h3><p className="cred-org">{c.org}</p><p>{c.desc}</p><div className="cred-meta"><span>{c.date}</span><span>{c.meta}</span></div></div></article>)}</div></div></section>}
function Contact(){const[form,setForm]=useState({name:'',email:'',message:''});const[sent,setSent]=useState(false);const submit=e=>{e.preventDefault();setSent(true);setForm({name:'',email:'',message:''})};return <section id="contact" className="section contact-section"><div className="container"><div className="contact-box"><div className="contact-copy"><span className="section-kicker">LET'S CONNECT</span><h2>Have an idea, opportunity or simply want to say hello?</h2><p>I'm open to learning, collaborating on meaningful student projects and connecting with people interested in technology.</p><div className="contact-links"><a href={'mailto:'+profile.email}><Mail/> {profile.email}</a><a href={'tel:'+profile.phone}><Phone/> {profile.phone}</a><a href={profile.linkedin} target="_blank" rel="noreferrer"><Globe/> LinkedIn profile <ExternalLink size={14}/></a></div></div><form onSubmit={submit}><label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Your name"/></label><label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="your@email.com"/></label><label>Message<textarea required rows="5" value={form.message} onChange={e=>setForm({...form,message:e.target.value})} placeholder="Write your message..."></textarea></label><button className="btn primary" type="submit">Send Message <ArrowUpRight size={17}/></button>{sent&&<div className="success">✓ Thank you! Your message has been recorded on this page.</div>}</form></div></div></section>}
function Footer(){return <footer><div className="container footer-inner"><div><strong>Ishvari<span>.</span></strong><p>Computer Science & AI/ML Undergraduate</p></div><div className="footer-right"><span>© 2026 Ishvari Swapnil Borsutkar</span><a href="#home">Back to top ↑</a></div></div></footer>}
function App(){const[active,setActive]=useState('home');const[darkMode,setDarkMode]=useState(()=>{const saved=localStorage.getItem('portfolio-theme');return saved?saved==='dark':false});useEffect(()=>{document.documentElement.setAttribute('data-theme',darkMode?'dark':'light');localStorage.setItem('portfolio-theme',darkMode?'dark':'light')},[darkMode]);useEffect(()=>{const ids=['home','about','education','skills','projects','credentials','contact'];const obs=new IntersectionObserver(entries=>{const v=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(v)setActive(v.target.id)},{rootMargin:'-25% 0px -60% 0px',threshold:[.05,.2,.5]});ids.forEach(id=>{const el=document.getElementById(id);if(el)obs.observe(el)});return()=>obs.disconnect()},[]);return <><Navbar active={active} darkMode={darkMode} onToggleTheme={()=>setDarkMode(!darkMode)}/><main><Hero/><About/><Education/><Skills/><Projects/><Credentials/><Contact/></main><Footer/></>};createRoot(document.getElementById('root')).render(<App/>);
